RMX1921: add missing blobs
* E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for libdirac-capiv2.so. (No such file or directory)
* E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for libdirac-capiv2-game.so.so. (No such file or directory)
* E RILD    : deviceInfoServiceModule dlopen failed ERROR:dlopen failed: library /vendor/lib64/deviceInfoServiceModule.so not found
..and so on